### ISSUE TITLE
labels are drawn wrong in the stacked layout

### ISSUE THREAD

**Issue by edzdez** [edzdez/sway-easyfocus#4]
![image](https://github.com/edzdez/sway-easyfocus/assets/31393290/a709ffa5-cc8d-4d7c-9d21-c065a8ffb535)

**Comment by markstos** [comment]
The issue is that the labels are being drawn exactly on top of each other. 

A solution is to track label window locations as we render them. Then, if the label windows would overlap, they are offset so they don't overlap any more. 

There is example code in wmfocus which handles this:

https://github.com/svenstaro/wmfocus/blob/53b4fb5bb327187c0d4717a6c5de4ca15328836b/src/main.rs

I took a look at implementing it here, but I can't figure out how to query the geometry of the `gtk::Fixed` widget. The Rust GTK3 docs are massive and hard to navigate.
